doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: '%database_driver%'
                charset: '%database_charset%'
                default_table_options:
                    charset: '%database_charset%'
                    collate: '%database_collation%'
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '%env(resolve:DATABASE_VERSION)%'

            repo1:
                url: '%env(resolve:REPO1_DATABASE_URL)%'
            repo2:
                url: '%env(resolve:REPO2_DATABASE_URL)%'

            # This connection is dedicated for SiteFactory to avoid known issues, should be the same as default
            site_factory:
                # configure these for your database server
                driver: '%database_driver%'
                charset: '%database_charset%'
                default_table_options:
                    charset: '%database_charset%'
                    collate: '%database_collation%'
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '%env(resolve:DATABASE_VERSION)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
