version: '3'

# https://doc.ezplatform.com/en/3.1/getting_started/requirements/

services:

  varnish:
    build: ./docker/varnish
    depends_on:
      - apache
    ports:
      - 8080:80

  apache:
    build: ./docker/apache
    depends_on:
      - redis
      - mariadb
      #- solr
    ports:
      - 8000:80
    volumes:
      - .:/var/www/ez:cached

  redis:
    image: redis:5.0
    #TODO: change maxmemory_policy to volatile-lru — https://doc.ezplatform.com/en/latest/guide/persistence_cache/

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root

  solr:
    build: ./docker/solr
    command:
      - solr-precreate
      - collection1
      - /opt/solr/server/solr/configsets/ezplatform
    ports:
      - 8983:8983

  elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node