version: '3'

# https://doc.ezplatform.com/en/3.2/getting_started/requirements/

services:

  varnish:
    build: ./docker/varnish
    depends_on:
      - apache
    ports:
      - 8080:80
    volumes:
      - ./vendor/ezsystems/ezplatform-http-cache/docs/varnish/vcl/varnish5.vcl:/etc/varnish/default.vcl:cached

  apache:
    build: ./docker/apache
    depends_on:
      - mariadb
    ports:
      - 8000:80
    volumes:
      - .:/var/www/ez:cached

  redis:
    image: redis:5.0
    #TODO: change maxmemory_policy to volatile-lru — https://doc.ezplatform.com/en/latest/guide/persistence_cache/

  memcached:
    image: memcached

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root

  solr:
    build: ./docker/solr
    command:
      - solr-precreate
      - collection1
      - /opt/solr/server/solr/configsets/ezplatform
    ports:
      - 8983:8983

  elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      #- http.cors.allow-origin=/.*/
      - http.cors.allow-origin=http://localhost:8035
    ports:
      - 9200:9200
      - 9300:9300

  elasticvue:
    image: cars10/elasticvue
    depends_on:
      - elasticsearch
    ports:
      - 8035:8080
