version: '3'

# https://doc.ibexa.co/en/4.0/getting_started/requirements/

services:

  varnish:
    build: ./docker/varnish
    depends_on:
      - apache
    ports:
      - 8080:80
    environment:
      - VARNISH_STORAGE=malloc,256m

  apache:
    build: ./docker/apache
    depends_on:
      - mariadb
    ports:
      - 8000:80
    volumes:
      - .:/var/www/ez:cached

  redis:
    image: redis:5.0

  memcached:
    image: memcached

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root

  solr:
    build: ./docker/solr
    command:
      - solr-precreate
      - collection1
      - /opt/solr/server/solr/configsets/ezplatform
    ports:
      - 8983:8983

  elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
